build:
  stage: build
  extends: .docker_dind
  timeout: 45m
  script:
    - sh .gitlab/ci/scripts/build.sh
  rules:
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - "**/*"
        - "!.gitlab/**"
        - "!.gitlab-ci.yml"
        - "!.github/**"
      variables:
        CI_PUBLISH_ENABLED: "true"
    - if: '$CI_COMMIT_REF_NAME == "stage" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - "**/*"
        - "!.gitlab/**"
        - "!.gitlab-ci.yml"
        - "!.github/**"
      variables:
        CI_PUBLISH_ENABLED: "true"
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: manual

deploy:
  extends: .deploy_ansible
  needs: []
  variables:
    SERVICE_NAME: documentation-unified
  rules:
    - if: '($CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_REF_NAME == "stage") && $CI_PIPELINE_SOURCE == "push"'
      variables:
        CI_DEPLOY_ENABLED: "true"
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: manual
      variables:
        CI_DEPLOY_ENABLED: "false"
